name: echo hello world
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: echo hello world
        run: |
          echo "Hello, world!"
          exit 0
  slack_notifier_if_success:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: test notice for slack if success
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07LVABK9K2' # 通知テスト用
          payload: |
            {
              "text": "XXXX（prd）のデプロイに成功しました",
              "attachments": [
                {
                  "color": "28a745",
                  "title": "https://github.com/kenshuhori/eleven-labo/",
                  "title_link": "https://github.com/kenshuhori/eleven-labo/",
                  "fields": [
                    {
                      "short": "true",
                      "title": "Status",
                      "value": "Success"
                    },
                    {
                      "short": "true",
                      "title": "ref_name",
                      "value": "${{ github.ref_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  slack_notifier_if_failure:
    needs: build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: test notice for slack if failure
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07LVABK9K2' # 通知テスト用
          payload: |
            {
              "text": "XXXX（prd）のデプロイに失敗しました",
              "attachments": [
                {
                  "color": "dc3545",
                  "title": "https://github.com/kenshuhori/eleven-labo/",
                  "title_link": "https://github.com/kenshuhori/eleven-labo/",
                  "fields": [
                    {
                      "short": "true",
                      "title": "Status",
                      "value": "Failure"
                    },
                    {
                      "short": "true",
                      "title": "ref_name",
                      "value": "${{ github.ref_name }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
