name: Bump New Patch
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  bump_new_patch:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Create new patch version
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          yarn version --patch --no-git-tag-version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Checkout new branch
        run: |
          echo "$(node -p "require('./package.json').version")"
          git checkout -b "bump-v$(node -p "require('./package.json').version")"
      - name: Echo new version
        run: |
          echo "New version: $(node -p "require('./package.json').version")"
      - name: Push new patch version
        run: |
          git add .
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
          git push origin HEAD
          gh pr create \
            --title "Bump version to $(node -p "require('./package.json').version")" \
            --body "Bump version to $(node -p "require('./package.json').version")" \
            --base main
      - name: Enable auto-merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
        run: |
          gh pr merge --merge --auto "$PR_URL"
