name: Create Patch Release Tag
on:
  pull_request:
    branches:
      - main
    types:
      - closed

permissions:
  pull-requests: read
  contents: write

jobs:
  create_patch_release_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Create new tag
        run: |
          export TAG_NAME="$(node -p "require('./package.json').version")"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
      - name: Create new release 
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.TAG_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          generate_release_note: true
