name: assume to deploy production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello world
        uses: ./.github/workflows/_echo_hello_world.yml
        id: echo_hello_world
        with:
          environment: production
      - name: test notice for slack
        if: steps.echo_hello_world.conclusion == 'success'
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07LVABK9K2' # 通知テスト用
          slack-message: "通知テスト : ${{ inputs.environment }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
