name: assume to deploy production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_echo_hello_world.yml
    with:
      environment: production
    secrets: inherit
