name: assume to deploy production

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_echo_hello_world.yml
    with:
      environment: production
    secrets: inherit
  slack_notifier_if_success:
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: test notice for slack if success
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07LVABK9K2' # 通知テスト用
          payload: |
            {
              "text": "XXXX（prd）のデプロイに成功しました",
              "attachments": [
                {
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "title_link": "https://github.com/kenshuhori/eleven-labo/",
                      "value": "Success"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  slack_notifier_if_failure:
    needs: build
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: test notice for slack if failure
        uses: slackapi/slack-github-action@v1.27.0
        with:
          channel-id: 'C07LVABK9K2' # 通知テスト用
          payload: |
            {
              "text": "XXXX（prd）のデプロイに失敗しました",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "dc3545",
                  "fields": [
                    {
                      "title": "Status",
                      "title_link": "",
                      "value": "Failure"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
