name: Release Patch Update
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  new_patch_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
      - name: Create new patch version
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "actions-user"
          yarn version --patch --no-git-tag-version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Checkout new branch
        run: |
          echo "$(node -p "require('./package.json').version")"
          git checkout -b "$(node -p "require('./package.json').version")"
      - name: Echo new version
        run: |
          echo "New version: $(node -p "require('./package.json').version")"
      - name: Push new patch version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git add .
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
          git push origin HEAD
          gh pr create \
            --title "Bump version to $(node -p "require('./package.json').version")" \
            --body "Bump version to $(node -p "require('./package.json').version")" \
            --base main
      # - name: Push new patch version
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   run: |
      #     git push origin HEAD
      # - name: Create new release tag
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      #   run: |
      #     git push origin main --tags
